### ISSUE TITLE
PageBuilderButtonTypes block saving

### ISSUE THREAD

**Issue by eichenlauba** [magento-devdocs/pagebuilder-examples#30]
Hi! 
Since i've installed the PageBuilderButtonTypes i can't save any page contain a slider or a banner (a infinitie loading appears).
If i uninstall this module the saving works again.

Have you any idea to solve this problem ?

Thanks for your help!
![Capture du 2021-06-22 11-12-06](https://user-images.githubusercontent.com/6337122/122897881-b1dca480-d34a-11eb-9002-9af09304c716.png)

**Comment by craigfleming** [comment]
@eichenlauba - I can confirm the issue you are experiencing using the Button/Extension example, but it is easily resolved by updating the following 2 files:

1. https://github.com/magento-devdocs/pagebuilder-examples/blob/master/Button/Extension/view/adminhtml/ui_component/pagebuilder_banner_form.xml
2. https://github.com/magento-devdocs/pagebuilder-examples/blob/master/Button/Extension/view/adminhtml/ui_component/pagebuilder_slide_form.xml

Replace `pagebuilder_base_form_with_background_attributes`

with `pagebuilder_base_form_with_background_video`

I'm using Magento v2.4.3 and this resolved the issue for me.

**Comment by bdenham** [comment]
Hey @eichenlauba and @craigfleming: I just merged a PR from @shelley113, who made the fix for `pagebuilder_slide_form.xml`. I will also merge the same fix for `pagebuilder_banner_form.xm` as @craigfleming mentioned above.

As mentioned to @shelley113, my sincere apologies for abandoning this site. It was not intentional. After I left the Page Builder team many months ago to join the Cloud team and the AdobeIO team, I thought I could take moments here and there to keep maintaining this repo. But alas, the workload from the other teams proved too much. 

But now I'm back in the fray working on the PWA Studio team, and will once again devote time to maintaining this repo and adding to it with a focus on Page Builder to PWA Studio integration examples. 

Again, sorry for the absence! And please consider adding PRs (and issues) now that someone is actively attending to this repo again. Thanks!
